sudo: false

branches:
  only:
  - master

if: branch = master AND env(TRAVIS_PULL_REQUEST) IS false

addons:
  apt:
    packages:
    - dblatex
    - dbtoepub
    - ditaa
    - doc-base
    - docbook
    - docbook-dsssl
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - docbook2odf
    - ghostscript
    - libbatik-java
    - pstoedit
    - python-pygments

notifications:
  email: false

script:
  - ./examples/build all
  - export PATH=$PATH:./bin/asciitosvg/
  - ./bin/buildpdfs
  - find -maxdepth 1 -type f \( -iname '*.pdf' -o -iname '*.epub' \)

before_deploy:
  - mkdir -p books
  - find -maxdepth 1 -type f \( -iname '*.pdf' -o -iname '*.epub' \) -exec mv -t books {} +

deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    commiter_from_gh: true
    local_dir: books
    github_token: $GH_PAGES_TOKEN
